export const tradeReducerActions = {
  CLEAR_TRADE: "CLEAR_TRADE",
  SET_TRADE: "SET_TRADE",
  SET_ORDER_ID : "SET_ORDER_ID",
  SET_SLICE_ID : "SET_SLICE_ID",
  SET_QUANTITY : "SET_QUANTITY",
  SET_PRICE : "SET_PRICE",
  SET_TIMESTAMP : "SET_TIMESTAMP",
  SET_BROKER : "SET_BROKER",
  SET_COMMENTS : "SET_COMMENTS",
}